name: ac327c3a-5264-40a2-8c6e-1e8d7c4b37ef
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - datashader
  - tensorflow=2.2.0
  - xarray=0.16.2
  - jupyter
  - hvplot
  - cartopy
  - pandas=1.0
  - iris=2.4
  - imageio=2.8
  - dask=2.11
